version: "3.9"

services:
  backend:
    build: services/backend
    command: uvicorn api.api:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
  frontend:
    build: services/frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true